### PR TITLE
Tests and Fixes for utils-networks-misc.R

### LINKED ISSUE #242: Tests for functionality in util-networks-misc.R
At the moment, we don't have tests for the functionality that is contained in `util-networks-misc.R` (e.g., retrieving expanded adjacency matrices, converting them to arrays, etc.). Parts of this functionality are used in the `showcase.R`, that is, we would see potential errors that are thrown during the run of `showcase.R`, but we don't test for the correctness of the functionality yet.

To make sure that the functionality is implemented correctly and to be able to spot deviations from the expected behavior when new package versions of package Matrix are released, it would be really helpful to have tests for the functionality that is contained in `util-networks-misc.R`.

### PR DESCRIPTION
**Pull request by Leo-Send**
### Prerequisites

- [x] I adhere to the coding conventions (described [here](../CONTRIBUTING.md)) in my code.
- [x] I have updated the copyright headers of the files I have modified.
- [x] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [x] I have put signed-off tags in *all* commits.
- [x] I have updated the changelog file [NEWS.md](../NEWS.md) appropriately.
- [x] I have checked whether I need to adjust the showcase file `showcase.R` with respect to my changes.
- [x] The pull request is opened against the branch `dev`.

### Description

This Pull request fixes #242 

### Added

- Add new `assert.sparse.matrices.equal` function to compare two sparse matrices for equality for testing purposes (PR #248, 9784cdf12d1497ee122e2ae73b768b8c334210d4, d9f1a8d90e00a634d7caeb5e7f8f262776496838)
- Add tests for file `util-networks.misc.R` for issue #242 (PR #248, f3202a6f96723d11c170346556d036cf087521c8, 030574b9d0f3435db4032d0e195a3d407fb7244b, 380b02234275127297fcd508772c69db21c216de, 8b803c50d60fc593e4e527a08fd4c2068d801a48, 7335c3dd4d0302b024a66d18701d9800ed3fe806, 6b600df04bec1fe70c272604f274ec5309840e65)

### Changed/Improved

- Enhance `get.author.names.from.network` and `get.author.names.from.data` to always have the same output format. Now it doesn't depend on the `global` flag anymore (PR #248, d87d32564156f13c83ebe3361c2b68e5d0ac16ac, ddbfe68d3e628e82f34e09b36fffe886646986c5)
- Change `util-tensor.R` to correctly use the new output format of `get.author.names.from.network` (PR #248, 72b663ebf7169c0da5c687fe215529f3be0c08c5)
- Fix `convert.adjacency.matrix.list.to.array` to throw an error if the function is called with wrong parameters (PR #248, ece2d38b4972745af3a83e06f32317a06465a345, 1a3e510df15f5fa4e920e9fce3e0e162c27cd6d1)
- Rename `compare.networks` to `assert.networks.equal` to better match the purpose of the function (PR #248, d9f1a8d90e00a634d7caeb5e7f8f262776496838)

### Fixed

- Fix `get.expanded.adjacency` to work if the provided author list does not contain all authors from network and add a warning when that happens since it causes some authors from the network to be lost in the resulting matrix (PR #248, ff59017e114b10812dcfb1704a19e01fc1586a13)
- Fix `get.expanded.adjacency.matrices` to have correct names for the columns and rows (PR #248, e72eff864a1cb1a4aecd430e450d4a6a5044fdf2)
- Fix `get.expanded.adjacency.cumulated` so that it works if `weighted` parameter is set to `FALSE` (PR #248, 2fb9a5d446653f6aee808cbfc87c2dafeb9a749a)

### CODE REVIEW

File: util-networks-misc.R [hunk 1]
```diff
@@ -194,16 +209,17 @@ get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
...
             if (!weighted) {
 
                 ## search for a non-zero entry and set them to an arbitray number (e.g., 42)
                 ## to force that all non-zero entries are correctly set to 1 afterwards
-                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
-                if (nrow(not.zero.idxs) > 0) {
-                    first.not.zero.idx = not.zero.idxs[1, ]
-                    names(first.not.zero.idx) = c("row", "col")
-                    matrices.cumulated[[m]][first.not.zero.idx[["row"]], first.not.zero.idx[["col"]]] = 42
+                if(length(matrices.cumulated[[m]]@i) > 0) {
```
Comment (hechtlC) [inline util-networks-misc.R:217]: space after if

File: util-networks-misc.R [hunk 2]
```diff
@@ -214,16 +230,35 @@ get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
...
 #' @param adjacency.list the list of adjacency matrices
 #'
 #' @return the converted array
 convert.adjacency.matrix.list.to.array = function(adjacency.list){
 
+    if (length(adjacency.list) < 1) {
+        logging::logerror("The method convert.adjacency.matrix.list.to.array received an empty list!")
+        stop("The method convert.adjacency.matrix.list.to.array received an empty list!")
+    }
+    ## Check if all matrices have equal colomn- and rownames
```
Comment (hechtlC) [inline util-networks-misc.R:244]: column

File: util-networks-misc.R [hunk 3]
```diff
@@ -214,16 +230,35 @@ get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
...
+    rownames = rownames(adjacency.list[[1]])
+    colnames = colnames(adjacency.list[[1]])
+
+    if (length(adjacency.list) > 1) {
+        for (i in 2 : length(adjacency.list)) {
+            if (!identical(rownames, rownames(adjacency.list[[i]])) || !identical(colnames, colnames(adjacency.list[[i]]))) {
+                error.string = sprintf("The matrix at position %d has a different col or rownames from the first!", i)
```
Comment (hechtlC) [inline util-networks-misc.R:251]: rowname nicht im plural

File: tests/test-util-networks-misc.R [hunk 4]
```diff
@@ -0,0 +1,825 @@
...
+    second.vertices = data.frame(
+        name = c("Detlef", "Dieter"),
+        kind = TYPE.AUTHOR,
+        type = TYPE.AUTHOR
+        )
+    second.edges = data.frame(
+        from = "Detlef",
+        to = "Dieter"
+        )
+    second.network = igraph::graph.data.frame(second.edges, directed = FALSE, vertices = second.vertices)
```
Comment (hechtlC) [inline tests/test-util-networks-misc.R:114]: Add a new line before the Act as you do in all other tests please

File: tests/test-util-networks-misc.R [hunk 5]
```diff
@@ -0,0 +1,825 @@
...
```
Comment (hechtlC) [inline tests/test-util-networks-misc.R:147]: same here

**Review by hechtlC — CHANGES_REQUESTED** [review]
The pull request looks good. Thanks for the new tests and the fixes @Leo-Send !
I have just found some small issues that need to be fixed. After they have been fixed and @bockthom is fine with the changes, we can merge the PR.

File: util-tensor.R [hunk 6]
```diff
@@ -93,7 +93,7 @@ FourthOrderTensor = R6::R6Class("FourthOrderTensor",
         initialize = function(networks, weighted = FALSE) {
 
             private$relations = names(networks)
-            private$authors = get.author.names.from.networks(networks)
+            private$authors = get.author.names.from.networks(networks)[[1]]
```
Comment (bockthom) [inline util-tensor.R:96]: Is this always correct?

File: tests/test-util-networks-misc.R [hunk 7]
```diff
@@ -0,0 +1,827 @@
...
+    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
+    proj.data.base = ProjectData$new(project.conf = proj.conf)
+    range.data = proj.data.base$get.data.cut.to.same.date("mails")
+
+    ## Act
+    result = get.author.names.from.data(data.ranges = list(range.data))
+    
+    ## Assert
+    expected = list(c("Björn", "Fritz fritz@example.org","georg", "Hans", 
+                    "Karl", "Olaf", "Thomas", "udo"))
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:182]: Indentation: "Karl" belongs to the vector, it should start below Björn.

File: tests/test-util-networks-misc.R [hunk 8]
```diff
@@ -0,0 +1,827 @@
...
+    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
+    proj.data.base = ProjectData$new(project.conf = proj.conf)
+    range.data = proj.data.base$get.data.cut.to.same.date("mails")
+
+    ## Act
+    result = get.author.names.from.data(data.ranges = list(range.data), globally = FALSE)
+    
+    ## Assert
+    expected = list(c("Björn", "Fritz fritz@example.org","georg", "Hans", 
+                    "Karl", "Olaf", "Thomas", "udo"))
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:199]: Indentation again.

File: tests/test-util-networks-misc.R [hunk 9]
```diff
@@ -0,0 +1,827 @@
...
+
+    ## Arrange
+    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
+    proj.data.base = ProjectData$new(project.conf = proj.conf)
+    range.data.one = proj.data.base$get.data.cut.to.same.date("mails")
+    range.data.two = proj.data.base$get.data.cut.to.same.date("issues")
+
+    ## Act
+    result = get.author.names.from.data(data.ranges = list(range.data.one, range.data.two), 
+                                                            data.sources = "issues", globally = FALSE)
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:270]: Indentation: `data.sources` should align with `data.ranges`.

File: tests/test-util-networks-misc.R [hunk 10]
```diff
@@ -0,0 +1,827 @@
...
+
+    ## Arrange
+    proj.conf = ProjectConf$new(CF.DATA, CF.SELECTION.PROCESS, CASESTUDY, ARTIFACT)
+    proj.data.base = ProjectData$new(project.conf = proj.conf)
+    range.data.one = proj.data.base$get.data.cut.to.same.date("mails")
+    range.data.two = proj.data.base$get.data.cut.to.same.date("issues")
+
+    ## Act
+    result = get.author.names.from.data(data.ranges = list(range.data.one, range.data.two), 
+                                                            data.sources = "commits", globally = FALSE)
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:288]: Indentation: `data.sources` should align with `data.ranges`.

File: tests/test-util-networks-misc.R [hunk 11]
```diff
@@ -0,0 +1,827 @@
...
+    edges = data.frame(
+        from = "Heinz",
+        to = "Dieter"
+        )
+    network.in = igraph::graph.data.frame(edges, directed = FALSE, vertices = vertices)
+    authors.in = c("Heinz", "Dieter", "Klaus")
+
+    matrix.out = Matrix::sparseMatrix(i = c(), j = c(), x = 0, 
+                                            dims = c(length(authors.in), length(authors.in)),
+                                            repr = "T")
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:314]: Indentation: `dims` and `repr` should align with `i`

File: tests/test-util-networks-misc.R [hunk 12]
```diff
@@ -0,0 +1,827 @@
...
+    edges = data.frame(
+        from = "Heinz",
+        to = "Dieter"
+        )
+    network.in = igraph::graph.data.frame(edges, directed = FALSE, vertices = vertices)
+    authors.in = c("Dieter", "Heinz")
+
+    matrix.out = Matrix::sparseMatrix(i = c(), j = c(), x = 0, 
+                                            dims = c(length(authors.in), length(authors.in)),
+                                            repr = "T")
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:347]: Indentation, see above.

File: tests/test-util-networks-misc.R [hunk 13]
```diff
@@ -0,0 +1,827 @@
...
+    rownames(matrix.out) = authors.in
+    colnames(matrix.out) = authors.in
+
+    matrix.out["Heinz", "Dieter"] = 1
+    matrix.out["Dieter", "Heinz"] = 1
+    
+    ## Act
+    result = get.expanded.adjacency(network =network.in, authors = authors.in)
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:355]: Missing space after `=`

File: tests/test-util-networks-misc.R [hunk 14]
```diff
@@ -0,0 +1,827 @@
...
+    edges = data.frame(
+        from = "Heinz",
+        to = "Dieter"
+        )
+    network.in = igraph::graph.data.frame(edges, directed = FALSE, vertices = vertices)
+    authors.in = c("Gerhardt", "Bob", "Dieter", "Heinz")
+
+    matrix.out = Matrix::sparseMatrix(i = c(), j = c(), x = 0, 
+                                            dims = c(length(authors.in), length(authors.in)),
+                                            repr = "T")
```
Comment (bockthom) [inline tests/test-util-networks-misc.R:413]: Indentation.

**Review by bockthom — CHANGES_REQUESTED** [review]
Looks good to me @Leo-Send, I only found "a few" indentation or formatting issues :wink: 
I am not sure if you use tabs or spaces during implementation - it might be that the wrong indentation comes from using tabs instead of spaces - if so, please configure your IDE in such a way that it does not use tabs.

And there is one line where the code should be made fail save (but nothing critical, so **no** need to adjust the NEWS), and sometimes an additional comment would be helpful. See my detailed comments below.

File: util-networks-misc.R [hunk 15]
```diff
@@ -194,16 +209,17 @@ get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
...
                 ## to force that all non-zero entries are correctly set to 1 afterwards
-                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
-                if (nrow(not.zero.idxs) > 0) {
-                    first.not.zero.idx = not.zero.idxs[1, ]
-                    names(first.not.zero.idx) = c("row", "col")
-                    matrices.cumulated[[m]][first.not.zero.idx[["row"]], first.not.zero.idx[["col"]]] = 42
+                if (length(matrices.cumulated[[m]]@i) > 0) {
+                
+                    row = matrices.cumulated[[m]]@i[[1]] + 1
+                    col = matrices.cumulated[[m]]@j[[1]] + 1
```
[the remark this answers is not in the document]
Comment (Leo-Send) [reply util-networks-misc.R:220]: I wrote 
'the first non-zero entry of a sparse matrix is at the first position pointed to by the lists @i and @j of the matrix. Since these lists store the position 0-based, but the list access we use them for is 1-based, we need to add 1 to both values'

is that okay? I do not really know how to explain it better than this.

File: util-tensor.R (hunk 6 above)
Comment (Leo-Send) [reply util-tensor.R:96]: Yes. If the 'globally' flag in the function call for 'get.author.names.from.networks' or 'get.author.names.from.data' is set, which is the default, the returned value is a list with a single entry, namely a vector with all the author names. Previous to my change to the return type of these functions, the returned value was that same vector without a list around it.

File: util-networks-misc.R (hunk 15 above)
[the remark this answers is not in the document]
Comment (bockthom) [reply util-networks-misc.R:220]: Sounds good! This is exactly the piece of information that is not easily extractable from the code itself. So, with this comment, it is understandable what's going on there.

Btw, please don't use the "@" symbol at the beginning of a word in comment on GitHub - this leads to automatically linking your comment to the GitHub users - so, by your comment, the users "i" and "j" were mentioned and subscribed to this PR. I guess we should avoid that if possible to not spam these users :wink: But no worries, I also did similar thinks some time ago, it just happens...

File: util-tensor.R (hunk 6 above)
Comment (bockthom) [reply util-tensor.R:96]: Ok, then it is fine. Thanks for the explanation. I just wanted to make sure that we don't overlook something here.

File: util-networks-misc.R (hunk 15 above)
[the remark this answers is not in the document]
Comment (Leo-Send) [reply util-networks-misc.R:222]: Right, I'll keep that in mind.

File: NEWS.md [hunk 16]
```diff
@@ -8,27 +8,28 @@
...
 - Rename `split.data.by.bins` into `split.dataframe.by.bins` as this it what it does (PR #244, ed5feb214a123b605c9513262f187cfd72b9e1f4)
-- Enhance `get.author.names.from.network` and `get.author.names.from.data` to always have the same output format, not depending on the `global` flag (PR #248, d87d32564156f13c83ebe3361c2b68e5d0ac16ac, ddbfe68d3e628e82f34e09b36fffe886646986c5)
-- Changed `util-tensor.R` to correctly use `get.author.names.from.network` function
+- Enhance `get.author.names.from.network` and `get.author.names.from.data` to always have the same output format. Now it doesn't depend on the `global` flag anymore (PR #248, d87d32564156f13c83ebe3361c2b68e5d0ac16ac, ddbfe68d3e628e82f34e09b36fffe886646986c5)
+- Change `util-tensor.R` to correctly use the new output format of `get.author.names.from.network` (PR #248, 72b663ebf7169c0da5c687fe215529f3be0c08c5)
+- Fix `convert.adjacency.matrix.list.to.array` to throw an error if the function is called with wrong parameters (PR #248, ece2d38b4972745af3a83e06f32317a06465a345, 1a3e510df15f5fa4e920e9fce3e0e162c27cd6d1)
```
Comment (bockthom) [inline NEWS.md:21]: Please avoid the word "Fix" at beginning of an item if the item does not belong to the "Fixed" category, that would be confusing.
Instead, I would suggest to simply start as follows: "Throw an error in `convert.adjacency.matrix.list.to.array` if..."

**Review by bockthom — APPROVED** [review]

**Review by hechtlC — APPROVED** [review]
